# Regenerates src/editor/Dictionary.gen.cpp from assets/dictionary/words.txt.
# Run from the repo root after editing the source word list:
#   .\tools\gen_dictionary.ps1
#
# Output: a single-statement initializer list of C-string literals — each word
# is its own literal (avoids MSVC's 65k-character single-literal limit).

param(
    [string]$Source = (Join-Path $PSScriptRoot '..\assets\dictionary\words.txt'),
    [string]$Target = (Join-Path $PSScriptRoot '..\src\editor\Dictionary.gen.cpp')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $Source)) {
    throw "Source word list not found at: $Source"
}

$words = [System.IO.File]::ReadAllLines($Source) |
         Where-Object { $_ -cmatch '^[a-z]+$' }

if ($words.Count -lt 1) {
    throw "Source word list is empty after filtering."
}

$sb = [System.Text.StringBuilder]::new($words.Count * 16)
[void]$sb.AppendLine('// AUTO-GENERATED by tools/gen_dictionary.ps1. DO NOT EDIT BY HAND.')
[void]$sb.AppendLine('// Regenerate after editing assets/dictionary/words.txt.')
[void]$sb.AppendLine('#include "Dictionary.gen.h"')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace retroedit {')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('const char* const kDictionaryWords[] = {')
foreach ($w in $words) {
    [void]$sb.Append('    "')
    [void]$sb.Append($w)
    [void]$sb.AppendLine('",')
}
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('')
[void]$sb.Append('const int kDictionaryWordCount = ')
[void]$sb.Append($words.Count)
[void]$sb.AppendLine(';')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('} // namespace retroedit')

[System.IO.File]::WriteAllText($Target, $sb.ToString(), [System.Text.Encoding]::ASCII)
Write-Host ("Wrote {0} words to {1}" -f $words.Count, $Target)
